# Generated by Django 3.1.4 on 2021-01-09 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_str', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('crn', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getcrndetails.course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_str', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('phase1_start_date', models.DateTimeField(blank=True, null=True, verbose_name='start of Phase 1 registration')),
                ('phase1_end_date', models.DateTimeField(blank=True, null=True, verbose_name='end of Phase 1 registration')),
                ('phase2_start_date', models.DateTimeField(blank=True, null=True, verbose_name='start of Phase 2 registration')),
                ('phase2_end_date', models.DateTimeField(blank=True, null=True, verbose_name='end of Phase 2 registration')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCapacities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_capacity', models.IntegerField(default=0)),
                ('seats_actual', models.IntegerField(default=0)),
                ('seats_remaining', models.IntegerField(default=0)),
                ('seats_waitlist_capacity', models.IntegerField(default=0)),
                ('seats_waitlist_actual', models.IntegerField(default=0)),
                ('seats_waitlist_remaining', models.IntegerField(default=0)),
                ('get_date', models.DateTimeField()),
                ('section_crn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getcrndetails.section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='latest_capacities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getcrndetails.sectioncapacities'),
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getcrndetails.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getcrndetails.semester'),
        ),
        migrations.AddConstraint(
            model_name='sectioncapacities',
            constraint=models.UniqueConstraint(fields=('section_crn', 'get_date'), name='unique_section_date'),
        ),
    ]
