# Generated by Django 3.1.4 on 2021-01-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getcrndetails', '0002_semester_semester_str_readable'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
