# Generated by Django 3.1.4 on 2021-01-12 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getcrndetails', '0003_section_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='latest_capacities',
        ),
    ]
